# Generated by Django 5.1.7 on 2025-07-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='agreed_terms',
            field=models.BooleanField(default=False),
        ),
    ]
