# Generated by Django 5.1.7 on 2025-07-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pendinguser_agreed_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
