# Generated by Django 5.1.7 on 2025-07-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_gender_userprofile_language_and_more'),
        ('users', '0003_alter_pendinguser_token'),
    ]

    operations = [
    ]
