# Generated by Django 5.1.7 on 2025-06-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='max_members',
            field=models.IntegerField(default=6),
        ),
    ]
