# Generated by Django 5.1.7 on 2025-07-02 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdg_action_plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sdgactionplan',
            name='allow_team_edit',
            field=models.BooleanField(default=True, help_text='允许团队成员编辑'),
        ),
        migrations.AddField(
            model_name='sdgactionplan',
            name='allow_team_view',
            field=models.BooleanField(default=True, help_text='允许团队成员查看'),
        ),
        migrations.AddField(
            model_name='sdgactionplan',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_action_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sdgactionplan',
            name='require_explicit_permissions',
            field=models.BooleanField(default=False, help_text='需要明确权限设置'),
        ),
        migrations.AddField(
            model_name='sdgactionplan',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewable_action_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sdgactionplan',
            name='plan_content',
            field=models.JSONField(default=dict),
        ),
    ]
