# Generated by Django 5.1.7 on 2025-07-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sdg_action_plan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sdgactionplan",
            name="google_doc_created",
            field=models.BooleanField(
                default=False, help_text="Whether Google Docs document has been created"
            ),
        ),
        migrations.AddField(
            model_name="sdgactionplan",
            name="google_doc_id",
            field=models.CharField(
                blank=True,
                help_text="Google Docs document ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sdgactionplan",
            name="google_doc_url",
            field=models.URLField(
                blank=True, help_text="Direct link to Google Docs document", null=True
            ),
        ),
        migrations.AddField(
            model_name="sdgactionplan",
            name="last_sync_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time content was synced to Google Docs",
                null=True,
            ),
        ),
    ]
