# Generated by Django 5.1.7 on 2025-07-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sdg_action_plan", "0002_sdgactionplan_allow_team_edit_and_more"),
        ("sdg_action_plan", "0002_sdgactionplan_google_doc_created_and_more"),
    ]

    operations = []
